CREATE TABLE task_parameter_base (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	TASK_ID INTEGER NOT NULL,
	NAME TEXT(255) NOT NULL,
	PARAMETER_TYPE INTEGER NOT NULL,
	PARAMETER_START_TIME INTEGER,
	PARAMETER_DURATION INTEGER,
	COMPARATOR STRING NOT NULL,
	PARAMETER_STATUS INTEGER
);